WITH GEN2 AS (
    SELECT C.ID
    FROM ECOLI_DATA C
    JOIN ECOLI_DATA P
    ON C.PARENT_ID = P.ID
    WHERE C.PARENT_ID IS NOT NULL AND P.PARENT_ID IS NULL
)
SELECT E.ID
FROM ECOLI_DATA E
RIGHT JOIN GEN2 G
ON E.PARENT_ID = G.ID
WHERE E.ID IS NOT NULL
ORDER BY E.ID ASC;