-- 코드를 입력하세요
SELECT DATE_FORMAT(B.SALES_DATE, '%Y') as YEAR, 
    DATE_FORMAT(B.SALES_DATE, '%m') as MONTH,
    count(DISTINCT B.USER_ID) as PUCHASED_USERS, 
    ROUND(COUNT(DISTINCT B.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) as PUCHASED_RATIO
FROM USER_INFO as A
JOIN ONLINE_SALE as B
ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;