SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)='2021'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U
ON S.USER_ID = U.USER_ID
WHERE YEAR(U.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;

/*
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), COUNT(DISTINCT USER_ID)
FROM ONLINE_SALE
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE);
*/