WITH RECURSIVE GEN1 AS(
    -- 1세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 2, ... 세대
    SELECT E.ID, E.PARENT_ID, G.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA E
    INNER JOIN GEN1 G
    ON E.PARENT_ID = G.ID
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM GEN1
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM GEN1 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC;
