WITH RECURSIVE GEN1 AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE 1=1
        AND PARENT_ID IS NULL
    UNION ALL
    SELECT ED.ID, ED.PARENT_ID, GEN1.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA ED
    INNER JOIN GEN1
    ON ED.PARENT_ID = GEN1.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN1
WHERE 1=1
    AND ID NOT IN (SELECT PARENT_ID FROM GEN1 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC;
