-- 식품 ID, 식품 이름, 총매출을 조회
SELECT O.PRODUCT_ID AS PRODUCT_ID, P.PRODUCT_NAME AS PRODUCT_NAME, (SUM(O.AMOUNT) * P.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
-- 생산일자가 2022년 5월
WHERE O.PRODUCE_DATE LIKE '2022-05-%'
GROUP BY PRODUCT_ID
-- 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;