WITH RECURSIVE hour_seq AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1
    FROM hour_seq
    WHERE hour < 23
)
SELECT H.HOUR AS HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM HOUR_SEQ H
LEFT JOIN ANIMAL_OUTS O
ON H.HOUR = HOUR(O.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;
