WITH MAX_SIZE_PER_YEAR AS (
    SELECT MAX(SIZE_OF_COLONY) MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    ABS(M.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA D
JOIN MAX_SIZE_PER_YEAR M
ON YEAR(DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV;